numerical_features:
  - "Temperature"
  - "Fuel_Price"
  - "CPI"
  - "Unemployment"

categorical_features:
  - Holiday_Flag

target: "Weekly_Sales"
# Model configuration
registered_model_name: "walmart-store-sales-regressor-code"
run_name: "walmart-sales-regressors"
artifact_path: "store-sales-regressor"